const STRINGS = {
    // Common
    APP_NAME: 'FitZing',
    WELCOME: 'Welcome',
    REGISTER: 'Register',
    LOGIN: 'Log In',
    LOGOUT: 'Logout',
    SIGN_UP: 'Sign Up',
    LOADING: 'Loading...',
    GO_BACK: 'Go Back',
    SEE_ALL: 'See all',
    VIEW_ALL: 'View all',
    HOME: 'Home',
    PROFILE: 'Profile',
    EDIT_PROFILE: 'Edit Profile',
    SAVE_CHANGES: 'Save Changes',
    PROFILE_UPDATED: 'Profile updated successfully',
    UPDATE_FAILED: 'Failed to update profile',

    // Auth Screens
    LOGIN_TITLE: 'Login to your account',
    LOGIN_SUBTITLE: 'Ready for your next tournament?',
    EMAIL: 'Email Address',
    PASSWORD: 'Password',
    FORGOT_PASSWORD: 'Forgot Password?',
    DONT_HAVE_ACCOUNT: "Don't have an account? ",
    ALREADY_HAVE_ACCOUNT: 'Already have an account? ',
    SIGNUP_TITLE: 'Create your account',
    SIGNUP_SUBTITLE: 'Join the sports community today',
    FIRST_NAME: 'First Name',
    LAST_NAME: 'Last Name',
    MOBILE: 'Mobile Number',
    BIRTH_DATE: 'Date of Birth',
    CITY: 'City',
    STATE: 'State',

    // Home Screen
    WELCOME_BACK: 'Welcome back,',
    EXCLUSIVE_TOURNAMENTS: 'Exclusive Tournaments',
    UPCOMING_EVENTS: 'Upcoming Events',
    EVENTS_JOINED: 'Events Joined',
    WINS: 'Wins',
    UPCOMING: 'Upcoming',
    ATHLETE_BADGE: 'Active Athlete',

    // Tournament Details
    ABOUT_TOURNAMENT: 'About Tournament',
    LOCATION: 'Location',
    STARTS: 'Starts',
    ENTRY_FEE: 'Entry Fee',
    CATEGORIES: 'Categories',
    REGISTER_NOW: 'Register Now',
    SHOW_MATCHES: 'Show Matches',
    TOURNAMENT_NOT_FOUND: 'Tournament not found',
    CREATE_TOURNAMENT: 'Create Tournament',
    TOURNAMENT_NAME: 'Tournament Name',
    DESCRIPTION: 'Description',
    LOCATION: 'Location',
    FORMAT: 'Format (e.g., knockout)',
    START_DATE: 'Start Date (YYYY-MM-DD)',
    END_DATE: 'End Date (YYYY-MM-DD)',
    ENTRY_FEE: 'Entry Fee',
    DISCOUNT: 'Discount (%)',
    CATEGORIES: 'Categories',
    ADD_CATEGORY: 'Add Category',
    CATEGORY_NAME: 'Category Name',
    SPONSORS: 'Sponsors',
    ADD_SPONSOR: 'Add Sponsor',
    SPONSOR_NAME: 'Sponsor Name',
    LOGO_URL: 'Logo URL',
    ORGANIZERS: 'Organizers',
    ADD_ORGANIZER: 'Add Organizer',
    ORGANIZER_NAME: 'Organizer Name',
    CONTACT_INFO: 'Contact Email/Phone',
    SUBMIT: 'Create Event',
    SAVING: 'Saving...',

    // Sidebar / Menu
    MY_EVENTS: 'My Events',
    NOTIFICATIONS: 'Notifications',
    MY_ACHIEVEMENTS: 'My Achievements',
    REFER_FRIEND: 'Refer a Friend',
    REWARDS_OFFERS: 'Rewards & Offers',
    SETTINGS: 'Settings',
    HELP_SUPPORT: 'Help & Support',
    BOOKINGS: 'Bookings',
    BOOKINGS_LIVE_SOON: 'Bookings will be live soon!',
    JOIN_LIVE_EVENTS: 'Till then, join live events and showcase your skills.',
};

export default STRINGS;
